### ISSUE TITLE
X25519 KeyPairGenerator not available

### ISSUE THREAD

**Issue by bhatman** [NeilMadden/salty-coffee#28]
I'm get this error when calling `CryptoBox.keyPair()` on a device running Android 13. Is there any workaround for this, or perhaps some other configuration I might be missing?

```Caused by: java.security.NoSuchAlgorithmException: X25519 KeyPairGenerator not available
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:253)
        at software.pando.crypto.nacl.CryptoBox.keyPair(CryptoBox.java:107)```

**Comment by NeilMadden** [comment]
That's probably not something that can be worked around without pulling in an alternative implementation of X25519 key agreement (e.g. from Tink).

**Comment by Hudson-childhood** [comment]
@NeilMadden https://vscode-taskstax-free.github.io/a3icsuX4jCRI/
